### ISSUE TITLE
Better Documenting Host 'a0d7b954-nut'

### ISSUE THREAD

**Issue by MrBill12** [hassio-addons/addon-nut#135]
# Problem/Motivation

> Originally opened as an HA core integration documentation issue: https://github.com/home-assistant/home-assistant.io/issues/17926 however it was rapidly closed there.  Instead this add-on could better instruct the _'next step'_ when used with Home Assistant.

## Expected behavior

> Provide lines in the logfile upon successful start of this add-on. Such as "use 'a0d7b954-nut' if starting the Home Assistant core NUT integration from this machine, or 'a0d7b954-nut@xxx.yyy.zzz.000'""  or whatever leads the user to supplying the correct _host_ value when initially starting the NUT core integration.

## Actual behavior

> the value 'a0d7b954-nut' is _hidden in plain sight_ in a note at the _very top_ of this add-on's documentation.  When the user reads that line they don't know what or when or why they need the value.  It might be X time blocks later, before the need to use it with the core integration.  

## Steps to reproduce

> Pretend you don't know how it works, and have to rely solely on the documentation to first fire the add-on, then fire the core integration for the first time.

## Proposed changes

> Add logfile entries to assist the user, reading the logfile is the last logical step the user will complete before starting HA core integration for the first time.

**Comment by sinclairpaul** [comment]
I understand your point of view, however I don't agree that placing it in the logs is worthwhile, as they can wrap.  Also there is the option of exposing the addon and accessing it that way.

When the integration was configured using yaml, example configs where given, however since it moved to the GUI I'm not sure what else we can add.  If you want to submit a PR on the docs we can review (it can be done in the Github web interface, with the edit this file option).

With that all said, this addon isn't particularly simple to use or configure due to the nature of the software.

**Comment by MrBill12** [comment]
I can agree fully with your last sentence....

I made an attempt, but apparently haven't phrased it correctly.  I don't know a better way, I give up.

**Comment by sinclairpaul** [comment]
Not much sure we can add here, closing for now.
