### ISSUE TITLE
How is it possible to use this addon in Home Assistant?

### ISSUE THREAD

**Issue by carsten-h** [hassio-addons/addon-nut#17]
I tried to add the repository: 
> https://github.com/hassio-addons/repository
like it is written in the readme, but Home Assitant don't let me add this!

What can be the problem? How can I use this addon in my Home Assitant installation?

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>

**Comment by dale3h** [comment]
Because this add-on is not yet available in the stable repo, you have to add the edge repo to be able to install it. Try adding this repo by URL: https://github.com/hassio-addons/repository-edge

Once added to Hass.io, you should see an additional section in your add-on store that is labeled “EDGE”. With the edge repo added to Hass.io, you should be able to install this add-on.

**Comment by carsten-h** [comment]
OK! Thank you very much for the information!
